//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterfloorAccountMaterial.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalAdress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LegalAdress()
        {
            this.partners_import = new HashSet<partners_import>();
        }
    
        public int Id { get; set; }
        public int IdIndexes { get; set; }
        public int IdArea { get; set; }
        public int IdCity { get; set; }
        public int IdStreet { get; set; }
        public string NumHouse { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual City City { get; set; }
        public virtual Indexes Indexes { get; set; }
        public virtual Street Street { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<partners_import> partners_import { get; set; }
    }
}
