//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterfloorAccountMaterial.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class partners_import
    {
        public int Id { get; set; }
        public int IdTypePartner { get; set; }
        public int IdNamePartner { get; set; }
        public int IdDirector { get; set; }
        public string Email { get; set; }
        public string PhoneNum { get; set; }
        public int IdLegalAdress { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual LegalAdress LegalAdress { get; set; }
        public virtual NamePartner NamePartner { get; set; }
        public virtual TypePartner TypePartner { get; set; }
    }
}
