//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterfloorAccountMaterial.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_import
    {
        public int Id { get; set; }
        public int IdTypeProduct { get; set; }
        public int IdNameProduct { get; set; }
        public string Articul { get; set; }
        public decimal MinCostForPartner { get; set; }
    
        public virtual NameProduct NameProduct { get; set; }
        public virtual TypeProduct TypeProduct { get; set; }
    }
}
