//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterfloor.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterFloorEntities : DbContext
    {
        private static masterFloorEntities _context;
        public masterFloorEntities()
            : base("name=masterFloorEntities")
        {
        }
        public static masterFloorEntities GetContext()
        {
            if(_context == null)
            {
                _context = new masterFloorEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<Indexes> Indexes { get; set; }
        public virtual DbSet<LegalAdress> LegalAdress { get; set; }
        public virtual DbSet<Material_type_import> Material_type_import { get; set; }
        public virtual DbSet<NamePartner> NamePartner { get; set; }
        public virtual DbSet<NameProduct> NameProduct { get; set; }
        public virtual DbSet<partner_products_import> partner_products_import { get; set; }
        public virtual DbSet<partners_import> partners_import { get; set; }
        public virtual DbSet<product_type_import> product_type_import { get; set; }
        public virtual DbSet<products_import> products_import { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypePartner> TypePartner { get; set; }
        public virtual DbSet<TypeProduct> TypeProduct { get; set; }
    }
}
