//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace masterfloor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class partner_products_import
    {
        public int Id { get; set; }
        public int IdNameProduct { get; set; }
        public int IdNamePartner { get; set; }
        public int CountOfProduct { get; set; }
        public System.DateTime DataOfSale { get; set; }
    
        public virtual NamePartner NamePartner { get; set; }
        public virtual NameProduct NameProduct { get; set; }
    }
}
